version: '3.4'

services:
  bookstore-backend:
    image: ${DOCKER_REGISTRY-}bookstorebackend
    container_name: BookStore-API
    build:
      context: .
      dockerfile: Bookstore-backend/Dockerfile 
      args:
        - DOTNET_ENV=Production
    depends_on:
         - db.books
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports: 
        - "8080:8080"
        - "8081:8081"  
  
  db.books:
      image: postgres:latest
      container_name: PostgreDb-Bookstore
      environment : 
        POSTGRES_PASSWORD: changethis
        POSTGRES_DB: booksdb
      ports:
      - "5432:5432"
      volumes:
         - postDb:/var/lib/postgresql/data
volumes:
  postDb:
    